AWSTemplateFormatVersion: '2010-09-09'
Description: Returns a Check Point Amazon Machine ID (20230110)
Parameters:
  Version:
    Description: Security Gateway or Management Server version
    Type: String
    Default: R80.40-PAYG-NGTP-GW
    AllowedValues:
    - R80.30-BYOL-MGMT
    - R80.30-PAYG-MGMT
    - R80.30-BYOL-GW
    - R80.30-PAYG-NGTP-GW
    - R80.30-PAYG-NGTX-GW
    - R80.40-PAYG-NGTP
    - R80.40-BYOL-MGMT
    - R80.40-PAYG-MGMT
    - R80.40-BYOL-GW
    - R80.40-PAYG-NGTP-GW
    - R80.40-PAYG-NGTX-GW
    - R81-PAYG-NGTP
    - R81-BYOL-MGMT
    - R81-PAYG-MGMT
    - R81-BYOL-GW
    - R81-PAYG-NGTP-GW
    - R81-PAYG-NGTX-GW
    - R81.10-PAYG-NGTP
    - R81.10-BYOL-MGMT
    - R81.10-PAYG-MGMT
    - R81.10-BYOL-GW
    - R81.10-PAYG-NGTP-GW
    - R81.10-PAYG-NGTX-GW
    - R81.20-PAYG-NGTP
    - R81.20-BYOL-MGMT
    - R81.20-PAYG-MGMT
    - R81.20-BYOL-GW
    - R81.20-PAYG-NGTP-GW
    - R81.20-PAYG-NGTX-GW
Mappings:
  ConverterMap:
    R80.30-BYOL-MGMT:
      Value: R8030BYOLMGMT
    R80.30-PAYG-MGMT:
      Value: R8030PAYGMGMT
    R80.30-BYOL-GW:
      Value: R8030BYOLGW
    R80.30-PAYG-NGTP-GW:
      Value: R8030PAYGNGTPGW
    R80.30-PAYG-NGTX-GW:
      Value: R8030PAYGNGTXGW
    R80.40-PAYG-NGTP:
      Value: R8040PAYGNGTP
    R80.40-BYOL-MGMT:
      Value: R8040BYOLMGMT
    R80.40-PAYG-MGMT:
      Value: R8040PAYGMGMT
    R80.40-BYOL-GW:
      Value: R8040BYOLGW
    R80.40-PAYG-NGTP-GW:
      Value: R8040PAYGNGTPGW
    R80.40-PAYG-NGTX-GW:
      Value: R8040PAYGNGTXGW
    R81-PAYG-NGTP:
      Value: R81PAYGNGTP
    R81-BYOL-MGMT:
      Value: R81BYOLMGMT
    R81-PAYG-MGMT:
      Value: R81PAYGMGMT
    R81-BYOL-GW:
      Value: R81BYOLGW
    R81-PAYG-NGTP-GW:
      Value: R81PAYGNGTPGW
    R81-PAYG-NGTX-GW:
      Value: R81PAYGNGTXGW
    R81.10-PAYG-NGTP:
      Value: R8110PAYGNGTP
    R81.10-BYOL-MGMT:
      Value: R8110BYOLMGMT
    R81.10-PAYG-MGMT:
      Value: R8110PAYGMGMT
    R81.10-BYOL-GW:
      Value: R8110BYOLGW
    R81.10-PAYG-NGTP-GW:
      Value: R8110PAYGNGTPGW
    R81.10-PAYG-NGTX-GW:
      Value: R8110PAYGNGTXGW
    R81.20-PAYG-NGTP:
      Value: R8120PAYGNGTP
    R81.20-BYOL-MGMT:
      Value: R8120BYOLMGMT
    R81.20-PAYG-MGMT:
      Value: R8120PAYGMGMT
    R81.20-BYOL-GW:
      Value: R8120BYOLGW
    R81.20-PAYG-NGTP-GW:
      Value: R8120PAYGNGTPGW
    R81.20-PAYG-NGTX-GW:
      Value: R8120PAYGNGTXGW
  RegionMap:
    cn-north-1:
      R8030BYOLGW: ami-0b4367e7f9ad0fa0b
      R8030BYOLMGMT: ami-075014546c995a089
      R8030PAYGMGMT: ami-0b9759bd10e27c0e5
      R8030PAYGNGTPGW: ami-0d420e709ad3ff9d9
      R8030PAYGNGTXGW: ami-07acf213d2d3fbbc6
      R8040BYOLGW: ami-09178d5412ac95f66
      R8040BYOLMGMT: ami-07be2d25689c5143b
      R8040PAYGMGMT: ami-081b0167326367035
      R8040PAYGNGTP: ami-066e53dbc44f71013
      R8040PAYGNGTPGW: ami-0dd05efa019447c49
      R8040PAYGNGTXGW: ami-0538218b6e674e267
      R8110BYOLGW: ami-0a82cd352ffa3c968
      R8110BYOLMGMT: ami-09e3e1e037172786c
      R8110PAYGMGMT: ami-06eb970fbb179f2da
      R8110PAYGNGTP: ami-0435d1ffb0383c491
      R8110PAYGNGTPGW: ami-0ecf9b7a8532474a2
      R8110PAYGNGTXGW: ami-0b5d5d8dbedddad71
      R8120BYOLGW: ami-0eb1cb04035370a81
      R8120BYOLMGMT: ami-0945a8f1ed7a1a0a8
      R8120PAYGMGMT: ami-09ed505d93f970e29
      R8120PAYGNGTP: ami-0b95baeb3ea27f4b3
      R8120PAYGNGTPGW: ami-025dfbdf5bfe6c218
      R8120PAYGNGTXGW: ami-02c38457b65ae2cd6
      R81BYOLGW: ami-0d2478ff2a939ed42
      R81BYOLMGMT: ami-04c7be5cd3796c325
      R81PAYGMGMT: ami-0e26432c0e335db61
      R81PAYGNGTP: ami-0fb6f391835cae224
      R81PAYGNGTPGW: ami-0cae7fa34a20fd7f8
      R81PAYGNGTXGW: ami-0e53294fc884a33c6
    cn-northwest-1:
      R8030BYOLGW: ami-01533c1c27ca309b1
      R8030BYOLMGMT: ami-01ef664ea6acd41d1
      R8030PAYGMGMT: ami-09fef9f8a371570a0
      R8030PAYGNGTPGW: ami-08259f9c3b5e2f816
      R8030PAYGNGTXGW: ami-0fb1ad56f928099f3
      R8040BYOLGW: ami-08d983d7e901ccacc
      R8040BYOLMGMT: ami-05a5f71bfea296492
      R8040PAYGMGMT: ami-08b47d6ea33147303
      R8040PAYGNGTP: ami-0e584683f3fdb8552
      R8040PAYGNGTPGW: ami-0516119fabc503dbe
      R8040PAYGNGTXGW: ami-039fc10700316f5ab
      R8110BYOLGW: ami-0538b4c37dfd08bf5
      R8110BYOLMGMT: ami-015bf020019cdd778
      R8110PAYGMGMT: ami-00702699b094d5ba8
      R8110PAYGNGTP: ami-0595f596ba5e0c639
      R8110PAYGNGTPGW: ami-0e12fae2e3d7e614f
      R8110PAYGNGTXGW: ami-02f1b2fe59c80e017
      R8120BYOLGW: ami-00169211e2c65e02c
      R8120BYOLMGMT: ami-016dd267edd3229c9
      R8120PAYGMGMT: ami-00a937641d843168d
      R8120PAYGNGTP: ami-0fd67c4a843380369
      R8120PAYGNGTPGW: ami-0196b5c8dc47b27e5
      R8120PAYGNGTXGW: ami-0c594321c5899567e
      R81BYOLGW: ami-0ec378edfa5cc574f
      R81BYOLMGMT: ami-07b3d5b6723466ff8
      R81PAYGMGMT: ami-0b47da4919e6459c0
      R81PAYGNGTP: ami-0b155095203add5de
      R81PAYGNGTPGW: ami-09a76fd70fe3ff3f1
      R81PAYGNGTXGW: ami-0551bf48395c02553
Resources:
  DummyHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
Outputs:
  ImageId:
    Description: Check Point Security Gateway AMI
    Value: !FindInMap [RegionMap ,!Ref 'AWS::Region', !FindInMap [ConverterMap, !Ref 'Version', Value]]
