AWSTemplateFormatVersion: '2010-09-09'
Description: Returns a Check Point Amazon Machine ID (20230110)
Parameters:
  Version:
    Description: Security Gateway or Management Server version
    Type: String
    Default: R81.10-BYOL-GW
    AllowedValues:
    - R80.30-BYOL-MGMT
    - R80.30-BYOL-GW
    - R80.40-BYOL-MGMT
    - R80.40-BYOL-GW
    - R81-BYOL-MGMT
    - R81-BYOL-GW
    - R81.10-BYOL-MGMT
    - R81.10-BYOL-GW
    - R81.20-BYOL-MGMT
    - R81.20-BYOL-GW
Mappings:
  ConverterMap:
    R80.30-BYOL-MGMT:
      Value: R8030BYOLMGMT
    R80.30-BYOL-GW:
      Value: R8030BYOLGW
    R80.40-BYOL-MGMT:
      Value: R8040BYOLMGMT
    R80.40-BYOL-GW:
      Value: R8040BYOLGW
    R81-BYOL-MGMT:
      Value: R81BYOLMGMT
    R81-BYOL-GW:
      Value: R81BYOLGW
    R81.10-BYOL-MGMT:
      Value: R8110BYOLMGMT
    R81.10-BYOL-GW:
      Value: R8110BYOLGW
    R81.20-BYOL-MGMT:
      Value: R8120BYOLMGMT
    R81.20-BYOL-GW:
      Value: R8120BYOLGW
  RegionMap:
    cn-northwest-1:
      R8030BYOLMGMT: ami-0c0a2663b3b48e699
      R8030BYOLGW: ami-01e5747983e0881a9
      R8040BYOLMGMT: ami-078b96162d6f70aa8
      R8040BYOLGW: ami-0b91d1ba9691c4ec2
      R81BYOLMGMT: ami-029e5fa437b2aa9ae
      R81BYOLGW: ami-03192b4d711b7ab72
      R8110BYOLMGMT: ami-05c5e5861ac9e9346
      R8110BYOLGW: ami-05de1daa6a6207297
      R8120BYOLMGMT: ami-057c429d11f2954a4
      R8120BYOLGW: ami-0ff904210943cf0da
    cn-north-1:
      R8030BYOLMGMT: ami-0da9988235844e6e2
      R8030BYOLGW: ami-0867e21301f6a5f63
      R8040BYOLMGMT: ami-0143512286ac9da90
      R8040BYOLGW: ami-0c715130e6dbf427a
      R81BYOLMGMT: ami-0dec88afe143b5bde
      R81BYOLGW:  ami-0283506ce747e634b
      R8110BYOLMGMT: ami-01f35bf5903d69bd9
      R8110BYOLGW: ami-082977187d6fa4240
      R8120BYOLMGMT: ami-0a38172c4482142ad
      R8120BYOLGW: ami-078b174c174528292
Resources:
  DummyHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
Outputs:
  ImageId:
    Description: Check Point Security Gateway AMI
    Value: !FindInMap [RegionMap ,!Ref 'AWS::Region', !FindInMap [ConverterMap, !Ref 'Version', Value]]
