AWSTemplateFormatVersion: '2010-09-09'
Description: Returns a Check Point Amazon Machine ID (20230110)
Parameters:
  Version:
    Description: Security Gateway or Management Server version
    Type: String
    Default: R81.20-BYOL-GW
    AllowedValues:
    - R80.30-BYOL-MGMT
    - R80.30-BYOL-GW
    - R80.40-BYOL-MGMT
    - R80.40-BYOL-GW
    - R81-BYOL-MGMT
    - R81-BYOL-GW
    - R81.10-BYOL-MGMT
    - R81.10-BYOL-GW
    - R81.20-BYOL-MGMT
    - R81.20-BYOL-GW
Mappings:
  ConverterMap:
    R80.30-BYOL-MGMT:
      Value: R8030BYOLMGMT
    R80.30-BYOL-GW:
      Value: R8030BYOLGW
    R80.40-BYOL-MGMT:
      Value: R8040BYOLMGMT
    R80.40-BYOL-GW:
      Value: R8040BYOLGW
    R81-BYOL-MGMT:
      Value: R81BYOLMGMT
    R81-BYOL-GW:
      Value: R81BYOLGW
    R81.10-BYOL-MGMT:
      Value: R8110BYOLMGMT
    R81.10-BYOL-GW:
      Value: R8110BYOLGW
    R81.20-BYOL-MGMT:
      Value: R8120BYOLMGMT
    R81.20-BYOL-GW:
      Value: R8120BYOLGW
  RegionMap:
    cn-north-1:
      R8030BYOLMGMT:
      R8030BYOLGW:
      R8040BYOLMGMT:
      R8040BYOLGW:
      R81BYOLMGMT:
      R81BYOLGW:
      R8110BYOLMGMT:
      R8110BYOLGW:
      R8120BYOLMGMT:
      R8120BYOLGW:
    cn-northwest-1:
      R8030BYOLMGMT:
      R8030BYOLGW:
      R8040BYOLMGMT:
      R8040BYOLGW:
      R81BYOLMGMT:
      R81BYOLGW:
      R8110BYOLMGMT:
      R8110BYOLGW:
      R8120BYOLMGMT:
      R8120BYOLGW:
Resources:
  DummyHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
Outputs:
  ImageId:
    Description: Check Point Security Gateway AMI
    Value: !FindInMap [RegionMap ,!Ref 'AWS::Region', !FindInMap [ConverterMap, !Ref 'Version', Value]]
